// GENERATED by scripts/scrape-unicef-prices.py --emit-ts — do not edit by hand.
// Merge into the corpus in src/data/index.ts (see SCRAPED_PRICE_PATCHES).

export const SCRAPED_PRICE_PATCHES: Record<string, { pricing: {
  catalogue: string; price: string; unit?: string; note?: string; url?: string;
}[] }> = {
  "artemether-lumefantrine": { pricing: [
    { catalogue: "UNICEF Supply Division", price: "US$12.25–14.7", unit: "per pack (as described)", note: "S1300062 Artemeth20mg+Lumefan120mg tabs/18/PAC-30", url: "https://www.unicef.org/supply/media/25546/file/Antimalarial-Medicines-price-data-May2026.pdf" },
    { catalogue: "UNICEF Supply Division", price: "US$15–17", unit: "per pack (as described)", note: "S1300063 Artemeth20mg+Lumefan120mg tabs/24/PAC-30", url: "https://www.unicef.org/supply/media/25546/file/Antimalarial-Medicines-price-data-May2026.pdf" },
    { catalogue: "UNICEF Supply Division", price: "US$0.84", unit: "per pack (as described)", note: "S1300084 Artemeth80mg+Lumefan480mg tab/6/PAC-1", url: "https://www.unicef.org/supply/media/25546/file/Antimalarial-Medicines-price-data-May2026.pdf" },
    { catalogue: "UNICEF Supply Division", price: "US$16.5", unit: "per pack (as described)", note: "S1300126 Artemeth80mg+Lumefan480mg tab/6/PAC-30", url: "https://www.unicef.org/supply/media/25546/file/Antimalarial-Medicines-price-data-May2026.pdf" },
  ] },
  "artesunate": { pricing: [
    { catalogue: "UNICEF Supply Division", price: "US$1.25–1.35", unit: "per pack (as described)", note: "S1300008 Artesunate pdr./inj 60mg vial/BOX-1", url: "https://www.unicef.org/supply/media/25546/file/Antimalarial-Medicines-price-data-May2026.pdf" },
    { catalogue: "UNICEF Supply Division", price: "US$1.35", unit: "per pack (as described)", note: "S1300013 Artesunate pdr./inj. 30mg vial/BOX-1", url: "https://www.unicef.org/supply/media/25546/file/Antimalarial-Medicines-price-data-May2026.pdf" },
    { catalogue: "UNICEF Supply Division", price: "US$2.4", unit: "per pack (as described)", note: "S1300014 Artesunate pdr./inj. 120mg vial/BOX-1", url: "https://www.unicef.org/supply/media/25546/file/Antimalarial-Medicines-price-data-May2026.pdf" },
    { catalogue: "UNICEF Supply Division", price: "US$13.2", unit: "per pack (as described)", note: "S1300130 Artesunate 50mg+SP 525mg tabs/3+1/PAC-25", url: "https://www.unicef.org/supply/media/25546/file/Antimalarial-Medicines-price-data-May2026.pdf" },
  ] },
  "chloroquine": { pricing: [
    { catalogue: "UNICEF Supply Division", price: "US$7.65", unit: "per pack (as described)", note: "S1531999 Chloroquine base 150mg tabs/PAC-10x10", url: "https://www.unicef.org/supply/media/25546/file/Antimalarial-Medicines-price-data-May2026.pdf" },
  ] },
  "primaquine": { pricing: [
    { catalogue: "UNICEF Supply Division", price: "US$3.34", unit: "per pack (as described)", note: "S1568102 Primaquine base 7.5mg tabs/PAC-10 x10", url: "https://www.unicef.org/supply/media/25546/file/Antimalarial-Medicines-price-data-May2026.pdf" },
    { catalogue: "UNICEF Supply Division", price: "US$28.28", unit: "per pack (as described)", note: "S1568106 Primaquine base 7.5mg tabs/PAC-1000", url: "https://www.unicef.org/supply/media/25546/file/Antimalarial-Medicines-price-data-May2026.pdf" },
  ] },
};
